TMTSystemsEngineering/DXL-Library-Files

TMT DXL Scripts/DRD Setup/bold_id.dxl

I edited 1 comment line in 1 file.

test commit 1

---

TMT DXL Scripts/Other/CR Preview DXL code (Obj Text OR CR Text).rtf
TMT DXL Scripts/Other/CR Redline Text.dxl
TMT DXL Scripts/Other/DXL move links for copied reqts.dxl
TMT DXL Scripts/Other/Documents Module DXL for Obj Text v7b.dxl
TMT DXL Scripts/Other/Remove Left Indent v2.dxl
TMT DXL Scripts/Other/Remove Links to Baselines.dxl
TMT DXL Scripts/Other/Set Module Owner Group Permissions.dxl
TMT DXL Scripts/Other/Set Module Permissions v5c.dxl
TMT DXL Scripts/Other/Set View Permissions v0.dxl
TMT DXL Scripts/Other/TMT_Find_Empty_Attrs.dxl
TMT DXL Scripts/Other/TMT_duplicateIDs_script.dxl
TMT DXL Scripts/Other/TMT_generate_latex_DRD.dxl

Adding new scripts that were not in orig release.

New Scripts

---

TMT DXL Scripts/Other/TMT_Copy_Obj_ID.dxl
TMT DXL Scripts/Other/TMT_Copy_Obj_ID_wZeros.dxl
TMT DXL Scripts/Other/TMT_List_Module_Stats.dxl
TMT DXL Scripts/Other/TMT_VCRM_from_VAM_link.dxl
TMT DXL Scripts/Other/csvimport_v1.dxl

New scripts added

---

TMT DXL Scripts/DRD Update/CRUtils.dxl
TMT DXL Scripts/DRD Update/processModCRs.dxl
TMT DXL Scripts/VCRM Management/VCRM_to_VA_links.dxl

Pathnames updated for include statements to be explicit for this
library collection to fix a run-time error.

include path update

---

TMT DXL Scripts/DRD Setup/drd_cleanup.dxl

Line 106: Changed "Figure Caption" to "Caption"
Line 115: Changed "Table Caption" to "Caption"
Line 158: Changed "Requirement" to "Normal"

Updated Paragraph Styles

---

TMT DXL Scripts/DRD Setup/drd_cleanup.dxl

Reverts TMTSystemsEngineering/DXL-Library-Files#7

Revert "Updated Paragraph Styles"

---

TMT DXL Scripts/Other/Set Module Owner Group Permissions.dxl
TMT DXL Scripts/Other/Set Module Permissions v5c.dxl

Changed 1 compliance attribute name & added 1 new attribute.  These 2 scripts use the affected attributes, so their names needed to be updated.

Compliance Attr Changes

---

TMT DXL Scripts/DRD Update/DRD Update.idx
TMT DXL Scripts/DRD Update/import_compliance_fields.dxl

Adds DXL script and menu tree item for importing compliance fields from
excel.

Add Compliance Import Feature

---

TMT DXL Scripts/DRD Update/ad_rd_obj.dxl

Added lines 375, 376 and 382 to include "if ADorRD = AD" statement

Fix RDs showing versions

---

TMT DXL Scripts/Other/Set Module Owner Group Permissions.dxl
TMT DXL Scripts/Other/Set Module Permissions v5c.dxl

4 attributes removed from the TMTattrs[] array.  Linked to… [OAD | OCD
| OPSRD | ORD].

Remove hardwired attributes

---

TMT DXL Scripts/DRD Setup/Remove_Left_Indent_v2.dxl

This is required to make it appear in the custom DOORS Menu

Add Comment to Left Indent Script

---

TMT DXL Scripts/SE Reports/SE Reports.idx
TMT DXL Scripts/SE Reports/old_adrd_thismodule.dxl

Update script to report old AD/RDs.  Add new script to handle current
module. Modify .idx file for menu entry.

Update SE Reports

---

TMT DXL Scripts/DRD Setup/drd_cleanup.dxl

This change fixes the issue that the OLE objects weren't consistently
being applied the same paragraph style. It also changes sections before
3 to Normal paragraph style.

Update DRD Cleanup Script

---

TMT DXL Scripts/Suspect Links/Suspect Links.hlp
TMT DXL Scripts/Suspect Links/Suspect Links.idx
TMT DXL Scripts/Suspect Links/audit_suspect_links.dxl
TMT DXL Scripts/Suspect Links/check_suspect_links.dxl
TMT DXL Scripts/Suspect Links/clear_all_suspect_links.dxl

Updates the dxl scripts and files for the suspect links menu to display
properly.

suspect links update

---

TMT DXL Scripts/Other/TMT_VCRM_from_VAM_link.dxl

Change method words to letters so the VCRM populates given the new VAM
template

Update VCRM from VAM script

---

TMT DXL Scripts/Other/VA Links Layout DXL.dxl

New script added for VA Links Layout DXL in DRD Modules

Add 1 dxl script

---

TMT DXL Scripts/VCRM Management/Link_VAs_to_DRDs.dxl
TMT DXL Scripts/VCRM Management/VCRM Management.hlp
TMT DXL Scripts/VCRM Management/VCRM Management.idx

New DXL script AND modified DXL menu tree files.

Initial upload of new DXL

---

TMT DXL Scripts/Other/TMT_VCRM_from_VAM_link.dxl
TMT DXL Scripts/VCRM Management/VCRM_to_VA_links.dxl

Small code updates and additional comments for DXL code mentioned in
the upcoming Verif Plans Document.

DXL Updates needed for Verif Plan Document

---

TMT DXL Scripts/Change Control Log/CR_Status_Update.dxl
TMT DXL Scripts/Change Control Log/Change Control Log.hlp
TMT DXL Scripts/Change Control Log/Change Control Log.idx

Adds DXL menu branch and DXL script to update CR Implementation Status
& Docs Affected & Docs Status & Docs No and Ver

Add Change Control Features

---

TMT DXL Scripts/Change Control Log/CR_Status_Update.dxl

Reset the boolean value so it will not think all ICDs are in DOORS.

Fixed ICD problem

---

TMT DXL Scripts/Change Control Log/CR_Status_Update.dxl

Fixes an out-of-control loop.  Due to the missing line to set a boolean
to false before starting a loop.

Updated script

---

TMT DXL Scripts/DRD Update/ad_rd_cr.dxl
TMT DXL Scripts/DRD Update/ad_rd_obj.dxl

Code updated to properly handle ADs and RDs marked as DELETE or DELETED

Fix Deleted AD RDs

---

TMT DXL Scripts/SE Reports/old_adrd_thismodule.dxl

Changed the output text so it is more readable.

Update SE Reports This Module

---

TMT DXL Scripts/DRD Update/ad_rd_cr.dxl
TMT DXL Scripts/DRD Update/ad_rd_obj.dxl

Adds: Delete, Deleted, delete, deleted

More Deleted Labels

---

TMT DXL Scripts/Change Control Log/CR_Status_Update.dxl
TMT DXL Scripts/DRD Update/ad_rd_cr.dxl
TMT DXL Scripts/DRD Update/ad_rd_obj.dxl
TMT DXL Scripts/Documents Register/AddDCCLinks.dxl
TMT DXL Scripts/SE Reports/old_adrd.dxl
TMT DXL Scripts/SE Reports/old_adrd_thismodule.dxl

Change "Documents Register" folder to "Document and CR Registers"

Updates Documents Register folder name in Scripts

---

TMT DXL Scripts/DRD Setup/drd_cleanup.dxl

fix DRD clean up for ICDs. IT requires: IS REQ and paragrph style to work in IOCD modules

fix DRD clean up

---

TMT DXL Scripts/DRD Setup/bold_id.dxl

BOld ID for ICD too

---

TMT DXL Scripts/Change Control Log/Change Control Log.hlp
TMT DXL Scripts/Change Control Log/Change Control Log.idx
TMT DXL Scripts/Change Control Log/WVR_Status_Update

Changes for the Waiver
